"use client";

import { useActionState } from "react";
import { addChild, type ChildActionState } from "@/app/actions/children";

export function AddChildForm() {
  const [state, action, pending] = useActionState<ChildActionState, FormData>(addChild, undefined);
  return <form action={action} className="space-y-4">{state?.message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<div><label htmlFor="name" className="mb-1 block text-sm font-medium text-slate-700">اسم الطفل</label><input id="name" name="name" required placeholder="أحمد محمد" className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500" />{state?.errors?.name && <p className="mt-1 text-sm text-red-600">{state.errors.name[0]}</p>}</div><div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="birthDate" className="mb-1 block text-sm font-medium text-slate-700">تاريخ الميلاد</label><input id="birthDate" name="birthDate" type="date" required className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500" />{state?.errors?.birthDate && <p className="mt-1 text-sm text-red-600">{state.errors.birthDate[0]}</p>}</div><div><label htmlFor="stage" className="mb-1 block text-sm font-medium text-slate-700">المرحلة الحالية</label><select id="stage" name="stage" className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500"><option value="">تحديد لاحقًا</option><option>استقبال</option><option>KG 1</option><option>KG 2</option><option>ابتدائي</option><option>إعدادي</option></select></div></div><div><label htmlFor="schoolGrade" className="mb-1 block text-sm font-medium text-slate-700">الصف الدراسي (اختياري)</label><input id="schoolGrade" name="schoolGrade" className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500" /></div><div><label htmlFor="notes" className="mb-1 block text-sm font-medium text-slate-700">ملاحظات تربوية</label><textarea id="notes" name="notes" rows={3} className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500" /></div><div><label htmlFor="medicalNotes" className="mb-1 block text-sm font-medium text-slate-700">ملاحظات طبية أو حساسية</label><textarea id="medicalNotes" name="medicalNotes" rows={2} className="w-full rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-blue-500" /></div><button type="submit" disabled={pending} className="w-full rounded-lg bg-blue-600 px-4 py-2.5 font-bold text-white hover:bg-blue-700 disabled:opacity-50">{pending ? "جاري الحفظ..." : "إضافة الطفل"}</button></form>;
}
