"use client";

import { useActionState } from "react";
import { createClassAsAdmin, type AdminActionState } from "@/app/actions/admin";

type TeacherOption = { id: string; name: string };

export function AdminCreateClassForm({ teacherOptions }: { teacherOptions: TeacherOption[] }) {
  const [state, action, pending] = useActionState<AdminActionState, FormData>(createClassAsAdmin, undefined);
  return <form action={action} className="space-y-4">{state?.message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<div><select name="teacherId" required defaultValue="" className="w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">اختر المدرس</option>{teacherOptions.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select>{state?.errors?.teacherId && <p className="mt-1 text-sm text-red-600">{state.errors.teacherId[0]}</p>}</div><div><input name="name" required placeholder="اسم الفصل" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.name && <p className="mt-1 text-sm text-red-600">{state.errors.name[0]}</p>}</div><div><input name="subject" required placeholder="المادة" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.subject && <p className="mt-1 text-sm text-red-600">{state.errors.subject[0]}</p>}</div><textarea name="description" rows={2} placeholder="وصف الفصل (اختياري)" className="w-full rounded-lg border border-slate-300 px-3 py-2" /><div className="grid gap-3 sm:grid-cols-3"><div><input name="pricePerHour" type="number" min="1" step="0.01" required placeholder="سعر الحصة" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.pricePerHour && <p className="mt-1 text-sm text-red-600">{state.errors.pricePerHour[0]}</p>}</div><div><input name="platformPercent" type="number" min="0" max="100" step="0.01" defaultValue="0" placeholder="نسبة المنصة ٪" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.platformPercent && <p className="mt-1 text-sm text-red-600">{state.errors.platformPercent[0]}</p>}</div><div><input name="fixedFee" type="number" min="0" step="0.01" defaultValue="0" placeholder="كلفة ثابتة" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.fixedFee && <p className="mt-1 text-sm text-red-600">{state.errors.fixedFee[0]}</p>}</div></div><button type="submit" disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-50">{pending ? "جاري الإنشاء..." : "إنشاء الفصل"}</button></form>;
}
