"use client";

import { useActionState } from "react";
import { createAcademyStage, createAcademyProgram, updateAcademyStage, type AcademyActionState } from "@/app/actions/academy";

export function StageCreateForm() {
  const [state, action, pending] = useActionState<AcademyActionState, FormData>(createAcademyStage, undefined);
  return <form action={action} className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><div><input name="name" required placeholder="اسم المرحلة" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.name && <p className="mt-1 text-xs text-red-600">{state.errors.name[0]}</p>}</div><input name="ageMin" type="number" min="2" max="14" required placeholder="من سن" className="rounded-lg border border-slate-300 px-3 py-2" /><input name="ageMax" type="number" min="2" max="14" required placeholder="إلى سن" className="rounded-lg border border-slate-300 px-3 py-2" /></div>{state?.errors?.ageMin && <p className="text-xs text-red-600">{state.errors.ageMin[0]}</p>}{state?.errors?.ageMax && <p className="text-xs text-red-600">{state.errors.ageMax[0]}</p>}<textarea name="description" rows={2} placeholder="وصف المرحلة (اختياري)" className="w-full rounded-lg border border-slate-300 px-3 py-2" /><button type="submit" disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{pending ? "جاري الحفظ..." : "إضافة المرحلة"}</button></form>;
}

export function ProgramCreateForm({ stages }: { stages: { id: string; name: string }[] }) {
  const [state, action, pending] = useActionState<AcademyActionState, FormData>(createAcademyProgram, undefined);
  return <form action={action} className="space-y-3">{state?.message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<select name="stageId" required defaultValue="" className="w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">اختر المرحلة</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select>{state?.errors?.stageId && <p className="text-xs text-red-600">{state.errors.stageId[0]}</p>}<input name="title" required placeholder="اسم البرنامج (مثال: المنهج الرسمي)" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.title && <p className="text-xs text-red-600">{state.errors.title[0]}</p>}<textarea name="description" rows={2} placeholder="وصف البرنامج (اختياري)" className="w-full rounded-lg border border-slate-300 px-3 py-2" /><textarea name="objectives" rows={2} placeholder="الأهداف (اختياري)" className="w-full rounded-lg border border-slate-300 px-3 py-2" /><button type="submit" disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{pending ? "جاري الحفظ..." : "إضافة البرنامج"}</button></form>;
}

export function StageEditForm({ stage }: { stage: { id: string; name: string; ageMin: number; ageMax: number; description: string | null } }) {
  const [state, action, pending] = useActionState<AcademyActionState, FormData>(updateAcademyStage, undefined);
  return <form action={action} className="mt-3 space-y-3 rounded-xl bg-white p-4 border border-slate-200"><input type="hidden" name="id" value={stage.id} /><div className="grid gap-3 sm:grid-cols-3"><input name="name" required defaultValue={stage.name} className="rounded-lg border border-slate-300 px-3 py-2" /><input name="ageMin" type="number" required defaultValue={stage.ageMin} className="rounded-lg border border-slate-300 px-3 py-2" /><input name="ageMax" type="number" required defaultValue={stage.ageMax} className="rounded-lg border border-slate-300 px-3 py-2" /></div>{state?.errors?.ageMin && <p className="text-xs text-red-600">{state.errors.ageMin[0]}</p>}{state?.errors?.ageMax && <p className="text-xs text-red-600">{state.errors.ageMax[0]}</p>}<textarea name="description" rows={2} defaultValue={stage.description ?? ""} className="w-full rounded-lg border border-slate-300 px-3 py-2" /><button type="submit" disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{pending ? "جاري الحفظ..." : "حفظ تعديلات المرحلة"}</button></form>;
}
