"use client";

import { useActionState } from "react";
import { createUser, type AdminActionState } from "@/app/actions/admin";

export function AdminCreateUserForm() {
  const [state, action, pending] = useActionState<AdminActionState, FormData>(createUser, undefined);
  return <form action={action} className="space-y-4">{state?.message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{state.message}</p>}<div><input name="name" required placeholder="الاسم كاملًا" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.name && <p className="mt-1 text-sm text-red-600">{state.errors.name[0]}</p>}</div><div><input name="email" required type="email" placeholder="الإيميل" dir="ltr" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.email && <p className="mt-1 text-sm text-red-600">{state.errors.email[0]}</p>}</div><div><input name="phone" required placeholder="رقم الموبايل (يبدأ بـ 01)" dir="ltr" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.phone && <p className="mt-1 text-sm text-red-600">{state.errors.phone[0]}</p>}</div><div><input name="password" required type="password" placeholder="كلمة المرور (8 حروف على الأقل)" className="w-full rounded-lg border border-slate-300 px-3 py-2" />{state?.errors?.password && <p className="mt-1 text-sm text-red-600">{state.errors.password[0]}</p>}</div><div><select name="role" required defaultValue="" className="w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">اختر الدور</option><option value="STUDENT">طالب</option><option value="TEACHER">مدرس</option><option value="PARENT">ولي أمر</option><option value="STAFF">أخصائي</option><option value="CASHIER">كاشير</option><option value="ADMIN">أدمن</option></select>{state?.errors?.role && <p className="mt-1 text-sm text-red-600">{state.errors.role[0]}</p>}</div><button type="submit" disabled={pending} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white disabled:opacity-50">{pending ? "جاري الإنشاء..." : "إنشاء الحساب"}</button></form>;
}
